class Commands:
    HELLO = "hello" 
    CLOSE = "close"
    EXIT = "exit"
    ADD = "add"
    CHANGE = "change"
    PHONE = "phone"
    DELETE = "delete"
    ALL = "all"

class Messages:
    Wellcome = "Welcome to the assistant bot!"
    EnterACommand = "Enter a command: "
    HowCanIHelpYou = "How can I help you?"
    InvalidCommand = "Invalid command."
    WrongParameters = "Wrong parameters"
    EnterUserName = "Enter user name"
    GiveNameAndPhone = "Give me name and phone please."
    ContactAlreadyExists = "Contact already exists"
    ContactDoesNotExist = "Contact does not exist" 
    ContactChanged = "Contact changed."
    ContactAdded = "Contact added."
    ContactDeleted ="Contact deleted."
    GoodBye = "Good bye!"